### ISSUE TITLE
RDTM is similar to Inverse k-Nearest Neighbor Maps

### ISSUE THREAD

**Issue by HartLen** [dk-liang/FIDTM#2]
I think the proposed RDTM is almost the same with Inverse k-Nearest Neighbor Maps in [1], except the name and experiments for localization.

[1] Improving Dense Crowd Counting Convolutional Neural Networks using Inverse k-Nearest Neighbor Maps and Multiscale Upsampling

**Comment by dk-liang** [comment]
> I think the proposed RDTM is almost the same with Inverse k-Nearest Neighbor Maps in [1], except the name and experiments for localization.
> 
> [1] Improving Dense Crowd Counting Convolutional Neural Networks using Inverse k-Nearest Neighbor Maps and Multiscale Upsampling

Thanks for your attention.  We do not think the RDTM is the same as the IKNN map, there are two crucial reasons: 1) IKNN map is a KNN distance map instead of a distance transform map. In other words, k-Nearest Neighbor is not the same as Distance Transform. In particular, R-DT is a special form of IKNN (when the K is set as 1). 2) The VISAPP paper is only a counting task instead of a localization task, and the localization task is one of our main contributions. To the best of our knowledge, we are the first to leverage the local maxima of the R-DT map for localization-based crowd counting. We will add discussion in the next version.
