### ISSUE TITLE
Huge or normal loss while training?

### ISSUE THREAD

**Issue by mariosconsta** [dk-liang/FIDTM#39]
![image](https://user-images.githubusercontent.com/22726730/229714828-7fcd4354-95c9-48cd-85ec-6db16103bc8e.png)

I get these values for loss while training the model from scratch on the JHU dataset. It started from ~10,000 and it is dropping slowly but I feel that this number is not right. In the code the for training_baseline the loss used is just MSE and not the one purposed in the paper, shouldn't this loss be in the range of 0 and 1?

**Comment by rydenisbak** [comment]
Hello, It is normal value of loss for `train_baseline.py` script, because loss do not have any type of normalization.
In my own experiments, I use normalization by number of heads and got losses like bellow for SHA dataset.


<img width="1300" alt="image" src="https://user-images.githubusercontent.com/16317197/231969376-16a576fc-4884-44fd-ba9b-579c5cfc2969.png">

**Comment by mariosconsta** [comment]
> Hello, It is normal value of loss for `train_baseline.py` script, because loss do not have any type of normalization. In my own experiments, I use normalization by number of heads and got losses like bellow for SHA dataset.
> 
> <img alt="image" width="1300" src="https://user-images.githubusercontent.com/16317197/231969376-16a576fc-4884-44fd-ba9b-579c5cfc2969.png">

Yes I've read this on another issue. I will normalize it as well and see the output, thank you!
